# Generated by Django 3.1.2 on 2020-12-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201224_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcartmodel',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='productcartmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
