# Generated by Django 3.1.2 on 2020-12-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201224_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcartmodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
