# Generated by Django 3.1.2 on 2020-12-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201224_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcartmodel',
            name='order',
        ),
    ]
