# Generated by Django 3.1.2 on 2020-12-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategoriesmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subproductcategoriesmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
