# Generated by Django 3.1.2 on 2021-01-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210112_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='date',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
